# scratch work

In [1]:
import jax

jax.config.update("jax_enable_x64", True)
import jax.numpy as jnp

from astropy.time import Time
import astropy.units as u
from astropy.coordinates import SkyCoord
from astroquery.jplhorizons import Horizons

from jorbit.utils.horizons import (
    horizons_bulk_vector_query,
    horizons_bulk_astrometry_query,
)

from jorbit import Particle

t0 = Time("2024-12-01 00:00")
t1 = Time("2025-12-01 00:00")

In [2]:
obj = Horizons(id="274301", location="@0", epochs=[t0.tdb.jd, t1.tdb.jd])
vecs = obj.vectors(refplane="earth")

x0 = jnp.array([vecs["x"][0], vecs["y"][0], vecs["z"][0]])
v0 = jnp.array([vecs["vx"][0], vecs["vy"][0], vecs["vz"][0]])

x1 = jnp.array([vecs["x"][-1], vecs["y"][-1], vecs["z"][-1]])
v1 = jnp.array([vecs["vx"][-1], vecs["vy"][-1], vecs["vz"][-1]])


obj = Horizons(id="274301", location="695", epochs=[t0.jd, t1.jd])
eph = obj.ephemerides(extra_precision=True, quantities="1")
coord0 = SkyCoord(eph["RA"][0], eph["DEC"][0], unit=(u.deg, u.deg), frame="icrs")
coord1 = SkyCoord(eph["RA"][-1], eph["DEC"][-1], unit=(u.deg, u.deg), frame="icrs")

In [3]:
p = Particle(x=x0, v=v0, time=t0, name="wikipedia", gravity="newtonian planets")
p.gravity(p._cartesian_state.to_system())

Array([[ 2.61030935e-05, -2.90119924e-05, -8.52860259e-06]], dtype=float64)

In [4]:
p = Particle(x=x0, v=v0, time=t0, name="wikipedia", gravity="newtonian solar system")
p.gravity(p._cartesian_state.to_system())

Array([[ 2.61030935e-05, -2.90119924e-05, -8.52860260e-06]], dtype=float64)

In [5]:
p = Particle(x=x0, v=v0, time=t0, name="wikipedia", gravity="gr planets")
p.gravity(p._cartesian_state.to_system())

Array([[ 2.61030932e-05, -2.90119921e-05, -8.52860250e-06]], dtype=float64)

In [6]:
p = Particle(x=x0, v=v0, time=t0, name="wikipedia", gravity="gr solar system")
p.gravity(p._cartesian_state.to_system())

Array([[ 2.61030932e-05, -2.90119921e-05, -8.52860250e-06]], dtype=float64)

In [7]:
p = Particle(x=x0, v=v0, time=t0, name="wikipedia", gravity="default solar system")
p.gravity(p._cartesian_state.to_system())

Array([[ 2.61030932e-05, -2.90119921e-05, -8.52860250e-06]], dtype=float64)

In [8]:
p1 = Particle(x=x0, v=v0, time=t0, name="wikipedia", gravity="newtonian solar system")
g1 = p1.gravity(p._cartesian_state.to_system())

p2 = Particle(x=x0, v=v0, time=t0, name="wikipedia", gravity="gr solar system")
g2 = p2.gravity(p._cartesian_state.to_system())

g1 - g2

Array([[ 3.11840184e-13, -3.20242656e-13, -9.39598774e-14]], dtype=float64)

In [ ]:
obj = Horizons(id="sun", location="@0", epochs=[t0.tdb.jd])
vecs = obj.vectors(refplane="earth")
x0 = jnp.array([vecs["x"][0], vecs["y"][0], vecs["z"][0]])
v0 = jnp.array([vecs["vx"][0], vecs["vy"][0], vecs["vz"][0]])

x0, v0

(Array([-0.00595056, -0.00446843, -0.00173775], dtype=float64),
 Array([ 7.01900351e-06, -3.66915239e-06, -1.71368420e-06], dtype=float64))

In [11]:
import jax

jax.config.update("jax_enable_x64", True)
import jax.numpy as jnp

from astropy.time import Time
import astropy.units as u
from astropy.coordinates import SkyCoord
from astroquery.jplhorizons import Horizons


from jorbit.ephemeris import Ephemeris

t0 = Time("2024-12-01 00:00")


eph = Ephemeris(ssos="default solar system")
jorbit_ephem = eph.state(t0)
jorbit_ephem

{'sun': {'x': <Quantity [-0.00595056, -0.00446843, -0.00173775] AU>,
  'v': <Quantity [ 7.01900351e-06, -3.66915239e-06, -1.71368420e-06] AU / d>,
  'log_gm': Array(-8.12544774, dtype=float64, weak_type=True)},
 'mercury': {'x': <Quantity [0.22698184, 0.19450601, 0.08041286] AU>,
  'v': <Quantity [-0.02463847,  0.01844025,  0.0124054 ] AU / d>,
  'log_gm': Array(-23.73665301, dtype=float64, weak_type=True)},
 'venus': {'x': <Quantity [ 0.71903244,  0.03069788, -0.03178175] AU>,
  'v': <Quantity [-0.00064329,  0.01833659,  0.00829192] AU / d>,
  'log_gm': Array(-21.045753, dtype=float64, weak_type=True)},
 'earth': {'x': <Quantity [0.34841989, 0.83982393, 0.36424903] AU>,
  'v': <Quantity [-0.01632825,  0.00560986,  0.00243177] AU / d>,
  'log_gm': Array(-20.82895848, dtype=float64, weak_type=True)},
 'mars': {'x': <Quantity [-0.12021452,  1.4264163 ,  0.65765611] AU>,
  'v': <Quantity [-1.34212094e-02,  2.57839855e-05,  3.74033655e-04] AU / d>,
  'log_gm': Array(-23.07194211, dtype=flo

In [58]:
# import numpy as np
# np.testing.assert_allclose(x0 - jorbit_ephem["sun"]["x"], 0.0, atol=1e-5)

horizon_names = [
    "sun",
    "mercury barycenter",
    "venus barycenter",
    "earth-moon barycenter",
    "mars barycenter",
    "jupiter barycenter",
    "saturn barycenter",
    "uranus barycenter",
    "neptune barycenter",
    "pluto barycenter",
]
jorbit_names = [
    "sun",
    "mercury",
    "venus",
    "earth",
    "mars",
    "jupiter",
    "saturn",
    "uranus",
    "neptune",
    "pluto",
]
for i in range(len(horizon_names)):
    obj = Horizons(id=horizon_names[i], location="@0", epochs=[t0.tdb.jd])
    vecs = obj.vectors(refplane="earth")
    x0 = jnp.array([vecs["x"][0], vecs["y"][0], vecs["z"][0]])
    v0 = jnp.array([vecs["vx"][0], vecs["vy"][0], vecs["vz"][0]])

    x_err = x0 - jorbit_ephem[jorbit_names[i]]["x"]
    v_err = v0 - jorbit_ephem[jorbit_names[i]]["v"]

    print(jorbit_names[i], x_err, v_err)
    print(jnp.linalg.norm(x_err), jnp.linalg.norm(v_err))
    assert (jnp.linalg.norm(x_err) * u.au) < 1 * u.m
    assert (jnp.linalg.norm(v_err) * u.au / u.day) < (1 * u.m / u.day)
    print()

sun [ 9.09862463e-16 -4.76181594e-16 -2.22695126e-16] [7.50471191e-19 1.40734524e-18 5.78523503e-19]
1.0508052777311424e-15 1.696619309748289e-18

mercury [-3.19544391e-12  2.39164244e-12  1.60894909e-12] [-2.80185597e-13 -2.39325920e-13 -9.88098492e-14]
4.303432641054524e-12 3.815026226767994e-13

venus [-8.33777491e-14  2.37817405e-12  1.07542447e-12] [-7.25749755e-14 -3.50761087e-15  3.00801051e-15]
2.6113600745980903e-12 7.272192610419289e-14

earth [-2.11730633e-12  7.27529148e-13  3.15414361e-13] [-1.41830991e-14 -3.38531286e-14 -1.46774953e-14]
2.260922594147187e-12 3.953003274298582e-14

mars [-1.74062154e-12  3.55271368e-15  4.85167462e-14] [ 1.10848830e-15 -1.39296296e-14 -6.41929001e-15]
1.7413011879935626e-12 1.5377600974074793e-14

jupiter [-9.58122470e-13  2.62012634e-13  1.35669254e-13] [-3.80771803e-16 -1.32966554e-15 -5.60966204e-16]
1.0025245306986708e-12 1.492541693828606e-15

saturn [1.04805054e-13 6.55031585e-13 2.66453526e-13] [-4.04407410e-16  7.11236625e-17  4.6

In [57]:
(1 * u.m / u.day).to(u.au / u.day)

<Quantity 6.68458712e-12 AU / d>

In [65]:
jorbit_names = [
    "ceres",
    "pallas",
    "juno",
    "vesta",
    "iris",
    "hygiea",
    "eunomia",
    "psyche",
    "euphrosyne",
    "europa",
    "cybele",
    "sylvia",
    "thisbe",
    "camilla",
    "davida",
    "interamnia",
]

horizons_names = [
    "1",
    "2",
    "3",
    "4",
    "7",
    "10",
    "15",
    "16",
    "31",
    "52",
    "65",
    "87",
    "88",
    "107",
    "511",
    "704",
]


for i in range(len(jorbit_names)):
    obj = Horizons(
        id=horizons_names[i], location="@0", epochs=[t0.tdb.jd], id_type="smallbody"
    )
    vecs = obj.vectors(refplane="earth")
    x0 = jnp.array([vecs["x"][0], vecs["y"][0], vecs["z"][0]])
    v0 = jnp.array([vecs["vx"][0], vecs["vy"][0], vecs["vz"][0]])

    x_err = x0 - jorbit_ephem[jorbit_names[i]]["x"]
    v_err = v0 - jorbit_ephem[jorbit_names[i]]["v"]

    print(jorbit_names[i], x_err, v_err)
    print(jnp.linalg.norm(x_err) * u.au.to(u.km), jnp.linalg.norm(v_err))
    assert (jnp.linalg.norm(x_err) * u.au) < 500 * u.km
    assert (jnp.linalg.norm(v_err) * u.au / u.day) < (2 * u.km / u.day)
    print()

ceres [ 1.55797930e-09  2.80592927e-09 -1.10484955e-11] [ 8.27463098e-14  6.60338190e-12 -1.23884084e-12]
0.4801290143863208 6.719094146987448e-12

pallas [-6.11944028e-07  1.06416595e-07  1.93889139e-07] [ 4.03827465e-10 -1.23703886e-09  7.99738295e-10]
97.34132201031923 1.5273909483473654e-09

juno [-3.61455983e-07  2.14067116e-07  9.70655557e-07] [-1.03430914e-09  1.23492553e-10 -2.66071414e-10]
158.2238743636404 1.075099905715805e-09

vesta [ 1.81260740e-09 -8.50033051e-08 -1.45548276e-08] [ 3.83449202e-10 -1.14445432e-11 -4.29685211e-11]
12.90422806956629 3.8601886257211927e-10

iris [-1.65800811e-07  7.08198469e-07  2.49115438e-07] [-3.84714895e-09  1.02736583e-09  9.54154564e-10]
115.01473865679188 4.0946851591660795e-09

hygiea [ 1.29125013e-08 -3.04120396e-08  1.78201962e-07] [ 1.05219508e-10 -1.39731212e-10  2.36974955e-10]
27.11296398310964 2.9453876816881584e-10

eunomia [-2.40212686e-07  1.31594779e-07 -1.20068202e-07] [-4.98995036e-10 -1.37234322e-09 -7.64656519e-10]
44.7